[build]
  base    = "site"
  publish = "dist"
  command = "npm run build"

[context.production]
  command = "hugo_0.18 server --theme=dimension --buildDrafts"

[context.deploy-preview]
  command = "npm run build-preview"
