baseurl = "https://moldecastro.netlify.com/"
title = "Dimension"
theme = "dimension"
languageCode = "pt-br"
defaultContentLanguage = "pt"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Mol de Castro Advogados"
  description = '<!--[-->Frase de efeito sobre o escritório de advocacia<!--]--><br />
                <!--[-->template gratuito da HTML5 UP sob a licença  <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
  logo = "fa-gavel"
  copyright = "Untitled"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.pt]
languageName = "Portugues"
weight = 1
title = "Mol de Castro Advocacia"

